/**
 * Episodic Memory (L3) — per-session/per-phase episode records.
 *
 * Phase A of memory-architecture-redesign. An "episode" is a closed phase
 * of work in a session: a summary of what happened, decisions made, open
 * questions, artifacts touched, and outcome status.
 *
 * Triggers (handled by callers, not this module):
 *   - status='done'      → emit episode for the active phase
 *   - anchor-change      → close current phase, start new one
 *   - idle-cutoff        → background job emits stalled phases
 *
 * Storage: <sessionDir>/episodes/<episodeId>.json + index.json
 * Immutable once written. Annotations append to a sidecar jsonl.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createLogger } from '../utils/debug.ts';

const log = createLogger('episode');

// ============================================================================
// Schema
// ============================================================================

export interface EpisodeAnchor {
  type: string;
  id: string;
  title?: string;
}

export interface EpisodePhase {
  /** First message ID covered by this episode (inclusive). */
  startMessageId: string | null;
  /** Last message ID covered (inclusive). null if still open at write time. */
  endMessageId: string | null;
  /** ISO timestamp of phase start. */
  startedAt: string;
  /** ISO timestamp of phase end (= episode close). */
  endedAt: string;
  /** Anchors active during this phase. Snapshot at close, not live. */
  anchors: EpisodeAnchor[];
}

export interface EpisodeArtifact {
  type: 'file' | 'feature' | 'plan' | 'commit' | 'pr' | 'other';
  /** path for file/plan, id for feature, sha for commit, url for pr. */
  ref: string;
  /** Optional human-readable label. */
  label?: string;
}

export type EpisodeOutcome = 'resolved' | 'blocked' | 'abandoned' | 'handoff' | 'unknown';

export type EpisodeCloseReason = 'session-done' | 'anchor-change' | 'idle-cutoff' | 'manual';

// ============================================================================
// Artifact graph — typed Rahmen-subgraph extracted by the L? agent
// ============================================================================

export type ArtifactConfidence = 'low' | 'medium' | 'high';

export interface ArtifactNode {
  /** One of `rahmen-taxonomy.ARTIFACT_TYPES.type`. Validated lazily. */
  type: string;
  /** Human-readable name, used for matching across episodes. */
  label: string;
  /** Message IDs (jsonl) that evidence this artifact's existence. */
  evidence: string[];
  /** Extractor's confidence — low entries deserve human review. */
  confidence: ArtifactConfidence;
  /** Optional orcha-CLI ID if the artifact is already persisted there. */
  ref?: string;
}

export interface ArtifactEdge {
  /** Reference to a node in this graph. Either "type:label" or "ref:<id>". */
  from: string;
  /** Reference to a node in this graph. */
  to: string;
  /** One of `rahmen-taxonomy.RELATION_TYPES.type`. */
  via: string;
}

export interface ArtifactGraph {
  nodes: ArtifactNode[];
  edges: ArtifactEdge[];
}

export interface Episode {
  /** Stable identifier, usable as cross-session reference. */
  id: string;
  /** Source session. */
  sessionId: string;
  /** Workspace the session belongs to (helps cross-workspace search). */
  workspaceId: string | null;
  /** Why this episode was emitted. */
  closeReason: EpisodeCloseReason;
  /** Phase covered. */
  phase: EpisodePhase;
  /**
   * 3-5 sentences. Generated by reflector when available; falls back to a
   * deterministic concatenation of decisions when no LLM is reachable.
   */
  summary: string;
  /** Observation IDs marked pivotal during this phase. */
  decisions: string[];
  /** Observation IDs marked question during this phase. */
  openQuestions: string[];
  /** Files / features / plans / commits referenced during the phase. */
  artifactsTouched: EpisodeArtifact[];
  /**
   * Typed Rahmen-subgraph extracted by the artifact-extractor agent.
   * Optional: episodes written before the extractor existed, or when it
   * was disabled, simply omit this field.
   */
  artifactGraph?: ArtifactGraph;
  /** Coarse outcome classification. */
  outcome: EpisodeOutcome;
  /** ISO write timestamp. */
  createdAt: string;
  /** Schema version — bump when structure changes. */
  schemaVersion: 1;
}

/**
 * Compact index entry — enables fast list-without-reading-all-files.
 * Keep in sync with episode write.
 */
export interface EpisodeIndexEntry {
  id: string;
  closeReason: EpisodeCloseReason;
  startedAt: string;
  endedAt: string;
  /** Phase-chaining: next episode starts after this message ID. */
  startMessageId: string | null;
  endMessageId: string | null;
  anchors: EpisodeAnchor[];
  outcome: EpisodeOutcome;
  summarySnippet: string;
  decisionsCount: number;
  openQuestionsCount: number;
  artifactsCount: number;
  /** Total nodes in the typed Rahmen-subgraph. 0 if no graph extracted. */
  artifactGraphNodeCount: number;
  /** Total edges in the typed Rahmen-subgraph. */
  artifactGraphEdgeCount: number;
}

export interface EpisodeIndex {
  schemaVersion: 1;
  entries: EpisodeIndexEntry[];
}

// ============================================================================
// Paths
// ============================================================================

export function episodesDir(sessionDir: string): string {
  return join(sessionDir, 'episodes');
}

export function episodePath(sessionDir: string, episodeId: string): string {
  return join(episodesDir(sessionDir), `${episodeId}.json`);
}

export function episodeIndexPath(sessionDir: string): string {
  return join(episodesDir(sessionDir), 'index.json');
}

export function episodeAnnotationsPath(sessionDir: string, episodeId: string): string {
  return join(episodesDir(sessionDir), `${episodeId}.annotations.jsonl`);
}

// ============================================================================
// Read
// ============================================================================

export function readEpisodeIndex(sessionDir: string): EpisodeIndex {
  const path = episodeIndexPath(sessionDir);
  if (!existsSync(path)) return { schemaVersion: 1, entries: [] };
  try {
    const raw = JSON.parse(readFileSync(path, 'utf-8')) as EpisodeIndex;
    if (raw && Array.isArray(raw.entries)) return raw;
  } catch (err) {
    log.debug('readEpisodeIndex: parse failed, returning empty', err);
  }
  return { schemaVersion: 1, entries: [] };
}

export function readEpisode(sessionDir: string, episodeId: string): Episode | null {
  const path = episodePath(sessionDir, episodeId);
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, 'utf-8')) as Episode;
  } catch {
    return null;
  }
}

export function listEpisodes(sessionDir: string): Episode[] {
  const dir = episodesDir(sessionDir);
  if (!existsSync(dir)) return [];
  const out: Episode[] = [];
  for (const name of readdirSync(dir)) {
    if (!name.endsWith('.json') || name === 'index.json') continue;
    if (name.endsWith('.annotations.jsonl')) continue;
    try {
      const ep = JSON.parse(readFileSync(join(dir, name), 'utf-8')) as Episode;
      out.push(ep);
    } catch {
      // skip corrupted
    }
  }
  // Newest first.
  return out.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

// ============================================================================
// Write
// ============================================================================

export interface WriteEpisodeArgs {
  sessionId: string;
  workspaceId?: string | null;
  closeReason: EpisodeCloseReason;
  phase: EpisodePhase;
  summary: string;
  decisions: string[];
  openQuestions: string[];
  artifactsTouched: EpisodeArtifact[];
  artifactGraph?: ArtifactGraph;
  outcome: EpisodeOutcome;
}

/**
 * Write a new episode. Episodes are immutable — re-writing the same id
 * is a no-op. Returns the written Episode.
 */
export function writeEpisode(sessionDir: string, args: WriteEpisodeArgs): Episode {
  const dir = episodesDir(sessionDir);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const ep: Episode = {
    id: `ep-${randomUUID()}`,
    sessionId: args.sessionId,
    workspaceId: args.workspaceId ?? null,
    closeReason: args.closeReason,
    phase: args.phase,
    summary: args.summary,
    decisions: args.decisions,
    openQuestions: args.openQuestions,
    artifactsTouched: args.artifactsTouched,
    ...(args.artifactGraph ? { artifactGraph: args.artifactGraph } : {}),
    outcome: args.outcome,
    createdAt: new Date().toISOString(),
    schemaVersion: 1,
  };

  const path = episodePath(sessionDir, ep.id);
  if (existsSync(path)) {
    // randomUUID collision is astronomically unlikely; if it ever happens,
    // bail rather than silently overwrite.
    throw new Error(`Episode id collision: ${ep.id}`);
  }
  // Atomic-enough write: full JSON, no partial state observable to readers.
  writeFileSync(path, JSON.stringify(ep, null, 2) + '\n', 'utf-8');

  upsertIndex(sessionDir, ep);
  return ep;
}

function upsertIndex(sessionDir: string, ep: Episode): void {
  const idx = readEpisodeIndex(sessionDir);
  const entry: EpisodeIndexEntry = {
    id: ep.id,
    closeReason: ep.closeReason,
    startedAt: ep.phase.startedAt,
    endedAt: ep.phase.endedAt,
    startMessageId: ep.phase.startMessageId,
    endMessageId: ep.phase.endMessageId,
    anchors: ep.phase.anchors,
    outcome: ep.outcome,
    summarySnippet: ep.summary.slice(0, 200),
    decisionsCount: ep.decisions.length,
    openQuestionsCount: ep.openQuestions.length,
    artifactsCount: ep.artifactsTouched.length,
    artifactGraphNodeCount: ep.artifactGraph?.nodes.length ?? 0,
    artifactGraphEdgeCount: ep.artifactGraph?.edges.length ?? 0,
  };
  // De-dup by id (defensive — id is uuid, collisions shouldn't happen).
  const filtered = idx.entries.filter((e) => e.id !== ep.id);
  filtered.push(entry);
  // Newest endedAt first.
  filtered.sort((a, b) => b.endedAt.localeCompare(a.endedAt));
  const updated: EpisodeIndex = { schemaVersion: 1, entries: filtered };
  writeFileSync(episodeIndexPath(sessionDir), JSON.stringify(updated, null, 2) + '\n', 'utf-8');
}

// ============================================================================
// Annotations (append-only sidecar)
// ============================================================================

export interface EpisodeAnnotation {
  /** ISO timestamp of the annotation. */
  at: string;
  /** Free-form note from the user or a downstream extractor. */
  note: string;
  /** Optional source label (e.g. 'user', 'semantic-extractor'). */
  source?: string;
}

export function appendAnnotation(
  sessionDir: string,
  episodeId: string,
  annotation: Omit<EpisodeAnnotation, 'at'> & { at?: string },
): void {
  const dir = episodesDir(sessionDir);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const entry: EpisodeAnnotation = {
    at: annotation.at ?? new Date().toISOString(),
    note: annotation.note,
    source: annotation.source,
  };
  const line = JSON.stringify(entry) + '\n';
  const path = episodeAnnotationsPath(sessionDir, episodeId);
  if (existsSync(path)) {
    const existing = readFileSync(path, 'utf-8');
    writeFileSync(path, existing + line, 'utf-8');
  } else {
    writeFileSync(path, line, 'utf-8');
  }
}

export function readAnnotations(sessionDir: string, episodeId: string): EpisodeAnnotation[] {
  const path = episodeAnnotationsPath(sessionDir, episodeId);
  if (!existsSync(path)) return [];
  const out: EpisodeAnnotation[] = [];
  for (const line of readFileSync(path, 'utf-8').split('\n')) {
    if (!line.trim()) continue;
    try {
      out.push(JSON.parse(line) as EpisodeAnnotation);
    } catch {
      // skip malformed
    }
  }
  return out;
}
